### ISSUE TITLE
wasm-opt is no longer present in the tinygo bundle since 0.22.0

### ISSUE THREAD

**Issue by birros** [schmir/asdf-tinygo#1]
**Is your feature request related to a problem? Please describe.**

Since version `0.22.0` of `tinygo`, `wasm-opt` binary is no longer included in the release bundle.

**Describe the solution you'd like**

So I created an asdf plugin for binaryen to make `wasm-opt` usable by tinygo.
Please consider adding these extra lines to your README to help users:

```shell
$ asdf plugin add binaryen https://github.com/birros/asdf-binaryen.git
$ asdf install binaryen latest
$ asdf local binaryen latest
$ wasm-opt --version
```

**Comment by schmir** [comment]
thanks for your feedback and sorry, I forgot about that issue. 
I've added a note now in 317070481f77719cc04e17543e23d8e210b73e8
